name: SimpleClan
version: ${project.version}
main: pvp.simpleClan.SimpleClan
api-version: 1.21
author: TremeQ
description: Rozbudowany plugin na klany z czatem, sojuszami, PvP toggle, statystykami i rankingiem
softdepend: [PlaceholderAPI]

commands:
  klan:
    description: Główna komenda klanów
    usage: /klan pomoc
    aliases: [clan, klany, clans]

permissions:
  simpleclan.create:
    description: Pozwala tworzyć klany
    default: true
  simpleclan.invite:
    description: Pozwala zapraszać do klanu
    default: true
  simpleclan.chat:
    description: Pozwala używać czatu klanowego i sojuszniczego
    default: true
  simpleclan.chat.color:
    description: Pozwala używać kolorów (&) w wiadomościach na czacie klanowym
    default: op
  simpleclan.alliance:
    description: Pozwala zarządzać sojuszami klanu
    default: true
  simpleclan.admin:
    description: Pozwala na administracyjne zarządzanie klanami (/klan admin)
    default: op
