name: SimpleClan
version: 2.0.0
main: pvp.simpleClan.SimpleClan
api-version: 1.21
author: TremeQ
description: Rozbudowany plugin na klany z czatem, PvP toggle, rankingiem i wieloma innymi funkcjami
softdepend: [PlaceholderAPI]

commands:
  klan:
    description: Główna komenda klanów
    usage: /klan <stworz|zapros|akceptuj|opusc|rozwiaz|lista|info|zastepca|degraduj|wyrzuc|chat|cc|kolor|pvp|ranking|pomoc>
    aliases: [clan, klany]

permissions:
  simpleclan.create:
    description: Pozwala tworzyć klany
    default: true
  simpleclan.invite:
    description: Pozwala zapraszać do klanu
    default: true
  simpleclan.chat:
    description: Pozwala używać czatu klanowego
    default: true
  simpleclan.admin:
    description: Pozwala na administracyjne zarządzanie klanami
    default: op